### ISSUE TITLE
[Bug]: Intune uses Type 01 serial number for 4k hash, DfciIdSupportGetSerialNumber should match expected serial number type

### ISSUE THREAD

**Issue by Flickdm** [Microsoft/mu_oem_sample#102]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

The current behavior is DfciIdSupportGetSerialNumber return the type 03 serial number instead of the intune expected serial number of type 01

https://github.com/microsoft/mu_oem_sample/blob/9174bf2dfa6f339633deefa28747097fb04b43fc/OemPkg/Library/DfciDeviceIdSupportLib/DfciDeviceIdSupportLib.c#LL209C1-L210C1

For example of what Intune expects see:
https://www.powershellgallery.com/packages/Get-WindowsAutoPilotInfo/3.5/Content/Get-WindowsAutoPilotInfo.ps1

### Expected Behavior

DfciIdSupportGetSerialNumber should return type 01 serial number

### Steps To Reproduce

Set the Type 01 and Type 03 serial numbers to different values
call DfciIdSupportGetSerialNumber  and compare against 
```powershell
Get-CimInstance -ClassName Win32_BIOS -Property SerialNumber  | Select-Object -ExpandProperty SerialNumber
```

### Build Environment

```markdown
- OS(s): Windows 11
- Tool Chain(s): VS2022
- Targets Impacted: RELEASE
```

### Version Information

```text
v2023020000.0.0
```

### Urgency

Medium

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by mikeytdisco** [comment]
The mu_tiano_platforms DfciDeviceIdSupportLib currently gets the Type1 Serial Number -    https://github.com/microsoft/mu_tiano_platforms/blob/ef89342c737e8e11c3ffa7e6d3630e216aed8415/QemuPkg/Library/DfciDeviceIdSupportLib/DfciDeviceIdSupportLib.c#L123
